// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALH2KsLn2WVmo1nDUCTNwCj66T2GO86yw',
    appId: '1:642119223126:web:539b602833f5307f5c78f7',
    messagingSenderId: '642119223126',
    projectId: 'smartledger-ai-beac1',
    authDomain: 'smartledger-ai-beac1.firebaseapp.com',
    storageBucket: 'smartledger-ai-beac1.firebasestorage.app',
    measurementId: 'G-MB0376WKYB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWCP-Yi9UjKBK9vVstAMAdYo93azl410w',
    appId: '1:642119223126:android:1f28dcaf8b8074f75c78f7',
    messagingSenderId: '642119223126',
    projectId: 'smartledger-ai-beac1',
    storageBucket: 'smartledger-ai-beac1.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3J7G_4HQ8-giRC7M6qe4jIfSoOvKEp9s',
    appId: '1:642119223126:ios:0b3c65e4a7954eda5c78f7',
    messagingSenderId: '642119223126',
    projectId: 'smartledger-ai-beac1',
    storageBucket: 'smartledger-ai-beac1.firebasestorage.app',
    iosBundleId: 'com.example.myFinance',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3J7G_4HQ8-giRC7M6qe4jIfSoOvKEp9s',
    appId: '1:642119223126:ios:0b3c65e4a7954eda5c78f7',
    messagingSenderId: '642119223126',
    projectId: 'smartledger-ai-beac1',
    storageBucket: 'smartledger-ai-beac1.firebasestorage.app',
    iosBundleId: 'com.example.myFinance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALH2KsLn2WVmo1nDUCTNwCj66T2GO86yw',
    appId: '1:642119223126:web:48592404486a99125c78f7',
    messagingSenderId: '642119223126',
    projectId: 'smartledger-ai-beac1',
    authDomain: 'smartledger-ai-beac1.firebaseapp.com',
    storageBucket: 'smartledger-ai-beac1.firebasestorage.app',
    measurementId: 'G-YHK1N06P9T',
  );
}
